#!/usr/bin/python2

import os,sys 
ROOT = os.path.dirname(__file__)+'/../../'
file = open(ROOT+'version','r')
lines = file.readlines() 
file.close() 
file = open(sys.argv[1],'a')
print >>file, 'Version:'+lines[0].split('=')[1]
file.close()



